name: SSH Server Deployment

on:
  push:
    branches:
      - server

  pull_request:
    branches:
      - server

jobs:
  ssh-folder-management:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Connect to SSH and perform operations
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" << 'EOF'
            # Delete the specified directory and its contents except for ecosystem.config.js
            cd /home/infovit-api/htdocs/api.infovit.us/
            find . -mindepth 1 -maxdepth 1 ! -name 'ecosystem.config.cjs' ! -name 'public' -exec rm -rf {} +



            # Remove any existing content in the director
            rm -rf /home/infovit-api/htdocs/api.infovit.us

            # Clone the specific branch of the GitHub repository into the Pharma director
            git clone -b server https://github.com/danial117/Pharma.git ./git

            # Change to the directory and install dependencie
            rm -rf ./git
            cd /home/infovit-api/htdocs/api.infovit.us/
            npm install
          
            # Start the application with pm2
            pm2 start ecosystem.config.cjs --env production

           
          EOF
